### ISSUE TITLE
"An Introduction to SegWit" links to an expired domain segwit.org

### ISSUE THREAD

**Issue by vasild** [chaincodelabs/study-groups#11]
The link "An Introduction to SegWit" from https://github.com/chaincodelabs/study-groups/tree/6e6a06a/segwit links to https://segwit.org/understanding-segregated-witness-905cc712c692, but `https` on that host is off and http://segwit.org shows

> This domain name expired on 2020-03-18 09:15:49

It is not clear whether the owner abandoned it, or just forgot to renew it (in which case it may be back soon).

I couldn't find a copy of that article elsewhere.

**Comment by adamjonas** [comment]
Thanks for the catch @vasild. I've opened #12 to address.
