### ISSUE TITLE
2 video suggestions for bitcoin basics

### ISSUE THREAD

**Issue by renepickhardt** [chaincodelabs/study-groups#2]
not sure where to put those: 

1. basics of electronic cash as a list of digital signatures: https://www.youtube.com/watch?v=TrF9RmfyLbw&t=4s
2. disecting a P2PKH tx: https://www.youtube.com/watch?v=1n4g3eYX1UI

didn't feel right at any of the places thus no pull request but an issue with these suggestions

**Comment by adamjonas** [comment]
closed by https://github.com/chaincodelabs/bitcoin-curriculum/pull/9
